### ISSUE TITLE
Setup Kanban

### ISSUE THREAD

**Issue by OscarFMdev** [OscarFMdev/recipe-inventory#10]
# Issue description 📄 

In this part of the project we set up the Kanban for the project and divided the activities:

- [Student 1] = @Shedrack-Sunday 
- [Student 2] = @OscarFMdev 

Link: https://github.com/users/OscarFMdev/projects/5

**Comment by julie-ify** [comment]
Hi @OscarFMdev and @Shedrack-Sunday,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You need to provide the link to your kanban board

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by GzimAsani** [comment]
Hi @OscarFMdev and @Shedrack-Sunday , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

The link that you've provided here is broken and is leading to a 404 page. Kindly update it
![image](https://user-images.githubusercontent.com/62705947/217021612-7baf1b5d-43f8-401f-aa91-695494e7ad13.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by julie-ify** [comment]
Hi @OscarFMdev and @Shedrack-Sunday,

## Highlights!
- Descriptive pull request ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
